name: Cryptic Frontend

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Environment information
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version
          echo "Google Chrome version:"
          google-chrome --version
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        run: npm ci
      - name: Production build
        run: './node_modules/@angular/cli/bin/ng build --prod'
      - name: Test
        run: './node_modules/@angular/cli/bin/ng test --browsers ChromeHeadless --watch=false'

#      TODO: re-add when we begin use end to end tests
#      - name: Run end to end tests
#        run: |
#          ./node_modules/protractor/bin/webdriver-manager update --standalone false --gecko false --versions.chrome $(google-chrome --version | cut -d ' ' -f 3)
#          ./node_modules/@angular/cli/bin/ng e2e --webdriver-update=false
